language: c

sudo: false

services:
  - postgresql
  - mysql

addons:
  apt:
    packages:
      - libgmp-dev
      - postgresql-client
      - postgresql-server-dev-all

env:
 - GHCVER=7.10
 - GHCVER=8.0

install:
  - export STACK_YAML=stack-$GHCVER.yaml
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version
  - createuser -s --no-password test
  - createdb -O test test

script:
  - stack setup
  - stack update
  - stack build
  - stack test --flag esqueleto:postgresql
  - stack test --flag esqueleto:-mysql

cache:
  directories:
  - $HOME/.stack
